// Created by Sabyasachi shadangi on 05/08/2012.
// Copyright 2012 sabyasachi shadangi. All rights reserved.




/**
 * @author sabyasachi shadangi
 * 
 * This supports response persistence and lifecycle events. 
 * New events are only accepted and persisted locally if prior events were acknowledged by 
 * upstream partner, otherwise an error occurs after a suitable wait/retry cycle. 
 * When prior events have been acknowledged by the TMS, new events generated by the client 
 * are acknowledged by the local servlet as soon as they are securely persisted locally, allowing 
 * the user to continue. Delay (and ultimately, in severe cases, interruption) of test thus only 
 * occur if upstream response time exceeds user 'think' time. To ensure that no responses are 
 * lost, an error is returned immediately in that case.
 */

#import "LoginResponseParser.h"
#import "ResponseParser.h"
#import "UtilityAction.h"
#ifdef CORDOVA_FRAMEWORK
#import <Cordova/CDVViewController.h>
#import "TTSUtil.h"
#else
#import "CDVViewController.h"
#endif

@interface PersistenceAction : NSObject <UIAlertViewDelegate> {
    NSMutableData * responseData;
    BOOL responseComplete;
    
}


@property (strong) NSString *loginResponseXML;
@property (retain) NSString *contentURI;
@property (retain) NSString *tmsURL;
- (id) init;

- (NSString *) login:(NSString *)xmlString;
- (NSString *) save:(NSString *)xmlString;
- (NSString *) feedback:(NSString *)xmlString;
- (NSString *) writeToAuditFile:(NSString *)xml;
- (NSString *) uploadAuditFile:(NSString *)xml;
- (NSString *) getProductType;

+(NSString *) updateRequired;
+ (NSString *) isGuidedAccessEnabled;


@end
